# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorreservoirs',
            name='region',
            field=models.CharField(max_length=1),
        ),
    ]
