# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20170925_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorreservoirs',
            options={'verbose_name': 'Major Reservoir', 'verbose_name_plural': 'Major Reservoirs'},
        ),
        migrations.AlterModelOptions(
            name='rwpas',
            options={'verbose_name': 'RWPA', 'verbose_name_plural': 'RWPAs'},
        ),
    ]
