# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_historicalaeriallinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalaeriallinks',
            options={'verbose_name': 'Historical Aerial Link', 'verbose_name_plural': 'Historical Aerial Links'},
        ),
    ]
