# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20170927_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('history', models.TextField()),
                ('section_one_header', models.CharField(max_length=50)),
                ('section_one_content', models.TextField()),
                ('section_two_header', models.CharField(max_length=50)),
                ('section_two_content', models.TextField()),
                ('section_three_header', models.CharField(max_length=50)),
                ('section_three_content', models.TextField()),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.MajorReservoirs')),
            ],
            options={
                'verbose_name_plural': 'Story Content',
                'verbose_name': 'Story Content',
            },
        ),
    ]
