# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_storycontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycontent',
            name='id',
        ),
        migrations.AlterField(
            model_name='storycontent',
            name='lake',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='map.MajorReservoirs'),
        ),
    ]
