# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20170928_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycontent',
            name='section_one_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storycontent',
            name='section_one_header',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='storycontent',
            name='section_three_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storycontent',
            name='section_three_header',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='storycontent',
            name='section_two_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storycontent',
            name='section_two_header',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
