# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20170928_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycontent',
            name='section_one_nav',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='storycontent',
            name='section_three_nav',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='storycontent',
            name='section_two_nav',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
