# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20170929_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycontent',
            name='section_one_nav',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='storycontent',
            name='section_three_nav',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='storycontent',
            name='section_two_nav',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
