# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20170929_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycontent',
            name='section_one_photo',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.related.OneToOneField>'),
        ),
    ]
