# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_storycontent_section_one_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycontent',
            name='section_one_photo',
            field=models.ImageField(blank=True, upload_to=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='map.MajorReservoirs')),
        ),
    ]
