# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20170929_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycontent',
            name='section_one_photo',
            field=models.ImageField(blank=True, upload_to=map.models.get_upload_path),
        ),
    ]
