# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20170929_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycontent',
            name='history_photo',
            field=models.ImageField(blank=True, upload_to=map.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='storycontent',
            name='section_three_photo',
            field=models.ImageField(blank=True, upload_to=map.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='storycontent',
            name='section_two_photo',
            field=models.ImageField(blank=True, upload_to=map.models.get_upload_path),
        ),
    ]
