# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_auto_20170929_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='LakeStatistics',
            fields=[
                ('lake', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='map.MajorReservoirs')),
                ('original_name', models.CharField(blank=True, max_length=50)),
                ('primary_purposes', multiselectfield.db.fields.MultiSelectField(choices=[('Flood Management', 'Flood Management'), ('Water Storage', 'Water Storage'), ('Hydroelectric Power', 'Hydroelectric Power')], max_length=50)),
            ],
        ),
    ]
