# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_lakestatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='lakestatistics',
            name='average_depth',
            field=models.FloatField(blank=True, help_text='Feet', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='construction_dates',
            field=models.CharField(blank=True, help_text='Ex. 1937 to 1942', max_length=50),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='dam_height',
            field=models.FloatField(blank=True, help_text='Feet', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='dam_width',
            field=models.FloatField(blank=True, help_text='Feet', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='discharge_capacity',
            field=models.TextField(blank=True, help_text='typically - Cubic Feet per Second'),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='full_elevation_gal',
            field=models.FloatField(blank=True, help_text='Gallons of Water', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='full_elevation_msl',
            field=models.FloatField(blank=True, help_text='Mean Sea Level', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='historic_high_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='historic_high_msl',
            field=models.FloatField(blank=True, help_text='Feet above Mean Sea Level', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='historic_low_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='historic_low_msl',
            field=models.FloatField(blank=True, help_text='Feet above Mean Sea Level', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='lake_area',
            field=models.FloatField(blank=True, help_text='Acres', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='lake_capacity',
            field=models.FloatField(blank=True, help_text='Acre-feet', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='length_of_lake',
            field=models.FloatField(blank=True, help_text='Miles', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='location',
            field=models.CharField(blank=True, help_text='Ex. Travis County, Texas', max_length=50),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='maximum_depth',
            field=models.FloatField(blank=True, help_text='Feet', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='maximum_width',
            field=models.FloatField(blank=True, help_text='Miles', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='miles_of_shoreline',
            field=models.FloatField(blank=True, help_text='Miles', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='num_of_floodgates',
            field=models.FloatField(blank=True, null=True, verbose_name='Number of Floodgates'),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='spillway_elevation',
            field=models.FloatField(blank=True, help_text='Feet above Mean Sea Level', null=True),
        ),
        migrations.AddField(
            model_name='lakestatistics',
            name='top_of_dam',
            field=models.FloatField(blank=True, help_text='Feet above Mean Sea Level', null=True),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='primary_purposes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Flood Management', 'Flood Management'), ('Water Storage', 'Water Storage'), ('Hydroelectric Power', 'Hydroelectric Power')], max_length=50),
        ),
    ]
