# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20171003_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lakestatistics',
            options={'verbose_name': 'Lake Statistics', 'verbose_name_plural': 'Lake Statistics'},
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='num_of_floodgates',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Floodgates'),
        ),
    ]
