# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_auto_20171004_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lakestatistics',
            name='average_depth',
            field=models.FloatField(blank=True, default=0, help_text='Feet'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='dam_height',
            field=models.FloatField(blank=True, default=0, help_text='Feet'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='dam_width',
            field=models.FloatField(blank=True, default=0, help_text='Feet'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='full_elevation_gal',
            field=models.FloatField(blank=True, default=0, help_text='Gallons of Water'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='full_elevation_msl',
            field=models.FloatField(blank=True, default=0, help_text='Mean Sea Level'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='historic_high_msl',
            field=models.FloatField(blank=True, default=0, help_text='Feet above Mean Sea Level'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='historic_low_msl',
            field=models.FloatField(blank=True, default=0, help_text='Feet above Mean Sea Level'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='lake_area',
            field=models.FloatField(blank=True, default=0, help_text='Acres'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='lake_capacity',
            field=models.FloatField(blank=True, default=0, help_text='Acre-feet'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='length_of_lake',
            field=models.FloatField(blank=True, default=0, help_text='Miles'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='maximum_depth',
            field=models.FloatField(blank=True, default=0, help_text='Feet'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='maximum_width',
            field=models.FloatField(blank=True, default=0, help_text='Miles'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='miles_of_shoreline',
            field=models.FloatField(blank=True, default=0, help_text='Miles'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='num_of_floodgates',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of Floodgates'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='spillway_elevation',
            field=models.FloatField(blank=True, default=0, help_text='Feet above Mean Sea Level'),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='top_of_dam',
            field=models.FloatField(blank=True, default=0, help_text='Feet above Mean Sea Level'),
        ),
    ]
