# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 15:50
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_auto_20171004_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lakestatistics',
            name='primary_purposes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Flood Management', 'Flood Management'), ('Water Storage', 'Water Storage'), ('Hydroelectric Power', 'Hydroelectric Power')], max_length=50, null=True),
        ),
    ]
