# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_auto_20171004_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignificantEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('High', 'High'), ('Low', 'Low')], default='High', max_length=4)),
                ('date', models.DateField()),
                ('height', models.FloatField(help_text='Feet above mean sea level')),
                ('drought', models.CharField(blank=True, help_text="Year range of drought (low events only). Example: '1947-57'", max_length=9)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.MajorReservoirs')),
            ],
            options={
                'verbose_name': 'Significant Event',
                'verbose_name_plural': 'Significant Events',
            },
        ),
    ]
