# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_significantevents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorreservoirs',
            options={'ordering': ['res_lbl'], 'verbose_name': 'Major Reservoir', 'verbose_name_plural': 'Major Reservoirs'},
        ),
    ]
