# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_auto_20171009_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorreservoirs',
            options={'verbose_name': 'Major Reservoir', 'verbose_name_plural': 'Major Reservoirs'},
        ),
    ]
