# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 20:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_auto_20171010_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatRamps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.MajorReservoirs')),
            ],
            options={
                'verbose_name': 'Boat Ramp',
                'verbose_name_plural': 'Boat Ramps',
            },
        ),
        migrations.CreateModel(
            name='ChannelMarkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd', models.IntegerField(blank=True)),
                ('marker_id', models.IntegerField(blank=True)),
                ('year', models.IntegerField(blank=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.MajorReservoirs')),
            ],
            options={
                'verbose_name': 'Channel Marker',
                'verbose_name_plural': 'Channel Markers',
            },
        ),
        migrations.CreateModel(
            name='Hazards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(blank=True, max_length=35)),
                ('num_buoys', models.CharField(blank=True, max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.MajorReservoirs')),
            ],
            options={
                'verbose_name': 'Hazard',
                'verbose_name_plural': 'Hazards',
            },
        ),
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_type', models.CharField(choices=[('Park', 'Park'), ('Undeveloped Recreation Area', 'Undeveloped Recreation Area'), ('Preserve', 'Preserve'), ('Park/Preserve', 'Park/Preserve')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('acres', models.FloatField(blank=True, default=0)),
                ('area', models.FloatField(blank=True, default=0)),
                ('perimeter', models.FloatField(blank=True, default=0)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.MajorReservoirs')),
            ],
            options={
                'verbose_name': 'Park',
                'verbose_name_plural': 'Parks',
            },
        ),
    ]
