# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_auto_20171011_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorreservoirs',
            name='story',
            field=models.CharField(choices=[('disabled', 'disabled'), ('enabled', 'enabled')], default='disabled', max_length=8),
        ),
    ]
