# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_auto_20171017_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycontent',
            name='history_photo_main',
            field=models.ImageField(blank=True, upload_to=map.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='storycontent',
            name='section_one_photo_main',
            field=models.ImageField(blank=True, upload_to=map.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='storycontent',
            name='section_three_photo_main',
            field=models.ImageField(blank=True, upload_to=map.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='storycontent',
            name='section_two_photo_main',
            field=models.ImageField(blank=True, upload_to=map.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='storycontent',
            name='summary_photo_main',
            field=models.ImageField(blank=True, upload_to=map.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='wdft_link',
            field=models.URLField(help_text='WDFT lake page link. Ex: https://waterdatafortexas.org/reservoirs/individual/travis', null=True),
        ),
    ]
