# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_auto_20171018_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorreservoirs',
            options={'ordering': ['res_lbl'], 'verbose_name': 'Major Reservoir', 'verbose_name_plural': 'Major Reservoirs'},
        ),
        migrations.AlterField(
            model_name='lakestatistics',
            name='wdft_link',
            field=models.URLField(blank=True, help_text='WDFT lake page link. Ex: https://waterdatafortexas.org/reservoirs/individual/travis', null=True),
        ),
    ]
