# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-11 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0033_auto_20190613_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RWPAs',
        ),
    ]
