# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-11 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0034_delete_rwpas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorreservoirs',
            name='region',
        ),
    ]
